Prereview4
vlad0k/wizard-form-react pull request #4
Opened 2020-10-20 14:03 UTC by vlad0k

2020-10-20 16:02 UTC, oleksandrbazil requested changes

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/Search/index.tsx
> +    const searchInDb = debounce(async () => {
?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/Search/index.tsx
> +        onBlur={() => setTimeout(() => setIsResultsShow(false), 500)}
убрать setTimeout 500

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/Search/index.tsx
> +import cn from 'classnames/dedupe';
?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/Search/index.tsx
> +                  image={avatar ? URL.createObjectURL(avatar) : undefined}
придумать что-то что бы не писать это каждый раз

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/StepWizard/FormLayout/index.tsx
> +    isSaved && setTimeout(() => setIsSaved(false), 5000);
use notification lib

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/StepWizard/FormLayout/index.tsx
> +      dispatch(nextStep());
почитать мне @oleksandrbazil

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +        {
?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/UserInfo/ValuesGroup/index.tsx
> +          <Button onClick={() => dispatch(selectStep(index))} appearance={ButtonAppearance.text}>
переписать на route

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/UserInfo/index.tsx
> +        {generatePageTemplate(user).map(({ key, value }: TemplateType, index) => (
переписать на <TagComponent></TagComponent>

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/UsersList/Paginator/index.tsx
> +const Paginator: FC<PaginatorPropsType> = ({ value, numberOfPages, selectPage = () => {} }) => {
Pagination вынести в отдельный компонент

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/UsersList/Table/index.tsx
> +                <td></td>
убрать

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/UsersList/index.tsx
> +      index > PORTION_SIZE * (page - 1) - 1 && index <= PORTION_SIZE * page - 1,
slice || split

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/UsersList/index.tsx
> +      {users.length / PORTION_SIZE > 0 && (
users.length / PORTION_SIZE > 0

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/UsersList/index.tsx
> +          selectPage={(page: number) => {
short function

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +            const avatar = new File([blob], 'avatar.jpeg');
а можно ли взять название файла из того что закинул пользователь? и добавить в него 150x150 (размеры)?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +  const [src, setSrc] = useState(URL.createObjectURL(image));
мне кажется или где-то еще есть такая конструкция? URL.createObjectURL(image)  ?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +    setSrc(URL.createObjectURL(image));
о, и тут

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +          onImageLoaded={(img) => setImg(img)}
imageLoadedHandler?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/index.tsx
> +                  <Avatar image={value && URL.createObjectURL(value)} />
ыыы

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/DatePicker/index.tsx
> +            setFieldValue(name, date ? date : undefined);
а почему нельзя установить значение по умолчанию?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/DatePicker/index.tsx
> +              <img className={classNames.icon} src={calendarIcon} alt="" />
кажется я где-то писал о том что нужно выносить в отдельный icon component, не так ли?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/Preloader/index.tsx
> +const Preloader = () => <img src={preloader} alt="Loading" />;
Loader

2020-10-20 16:02 UTC, oleksandrbazil commented on src/components/ui/SelectField/index.tsx
> +      {label && <FormLabel label={label} />}
второй раз вижу эту логику, лучше добавь ее в FormLabel

2020-10-20 16:02 UTC, oleksandrbazil commented on src/db/index.ts
> +  return await db.table('users').toArray();
а почему бы не вынести название таблицы ('users') в переменную?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/db/index.ts
> +  await db.table('users').put({ ...values, id, lastUpdated: new Date() });
для даты можно использовать суфикс `At` => updatedAt

2020-10-20 16:02 UTC, oleksandrbazil commented on src/db/index.ts
> +  db.table('users').delete(id);
а что произойдет если айдишник будет не числом? 
что произойдет если передать старый айдишник? (уже удаленного пользователя?)

2020-10-20 16:02 UTC, oleksandrbazil commented on src/db/index.ts
> +      user.lastname.toLowerCase().includes(search.toLowerCase()),
ты видишь то что вижу я?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/localStorage/index.ts
> +  return formState ? JSON.parse(formState) : undefined;
я считаю что проверка слабая. 
Форма у тебя какой тип данных? объект
а ты что проверяешь?
а если это объект то почему значение по умолчанию не пустой объект?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/IndexPage/index.module.css
> +  color: var(--finish-color);
а почему называется finish-color?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/IndexPage/index.tsx
> +    setTimeout(() => setIsJustGenerated(false), 5000);
👎

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/IndexPage/index.tsx
> +import { generateUsers } from '../../redux/usersListReducer';
а где обещанная сортировка импортов?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/IndexPage/index.tsx
> +    !isJustGenerated && dispatch(generateUsers());
то есть я могу генерировать пользователей раз в 5 секунд или каждый не четный клик на кнопку?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/users/AddPage/index.tsx
> +import { useDispatch } from 'react-redux';
где сортировка?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/users/EditPage/index.tsx
> +      const {
а почему так?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/users/EditPage/index.tsx
> +        submitStep({
submit step?? почему не submitForm?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/users/InfoPage/index.tsx
> +  if (!user) return <div />;
а почему тут эта проверка? где она должна быть?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/pages/users/ListPage/index.tsx
> +  <PageLayout name={'List of users'}>
вот за что ты так со мной?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/redux/stepWizardReducer.ts
> +  numberOfSteps: 0,
а почему numberOfSteps находиться в Redux?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/redux/stepWizardReducer.ts
> +    gender: null as 'male' | 'female' | null,
что это за конструкция? почему если null это male?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +import xhr from 'xhr';
можем обойтись fetch?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +  page: 1,
почему нам page нужен в Redux?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +    for (let i = 0; i < 50; i++) {
однако здравствуйте

2020-10-20 16:02 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +  2000,
что это?

2020-10-20 16:02 UTC, oleksandrbazil commented on src/yup/index.ts
> +Yup.addMethod<StringSchema>(Yup.string, 'uniqueUsername', function () {
то есть в проекте мы используем синтаксис ES6 а в этом файле ES5?

2020-10-22 14:20 UTC, oleksandrbazil requested changes

2020-10-22 14:20 UTC, oleksandrbazil commented on .eslintrc
> +}
end of line

2020-10-22 14:20 UTC, oleksandrbazil commented on jsconfig.json
> +}
EOL

2020-10-22 14:20 UTC, oleksandrbazil commented on src/components/Search/index.tsx
> +          {foundUsers.map(({ id, username, firstname, lastname, avatar = undefined }) => (
?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/components/StepWizard/AccountForm/index.tsx
> +    avatar: Yup.mixed().notRequired().fileSize(2),
почему 2 ?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/components/StepWizard/FormLayout/index.tsx
> +      dispatch(submitForm(values));
submitForm

2020-10-22 14:20 UTC, oleksandrbazil commented on src/components/StepWizard/TabPanel/index.tsx
> +  const tabClassName = cn(classNames.tab, {
[classNames.visited]: editMode || disabled

2020-10-22 14:20 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +            const avatar = new File([blob], 'avatar.png');
это получаеться что я теперь не смогу отправлять jpeg?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/index.tsx
> +            console.log(file);
WTF?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/db/index.ts
> +const USERS_TABLE_NAME = 'users';
а чего ниже ES5?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/pages/users/EditPage/index.tsx
> +        dispatch(
а зачем нам деструктуризация?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +      const user = users.find((user) => id === user.id);
деструктуризация?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +        animationIn: ['animate__animated', 'animate__fadeIn'],
snake_case vs camelCase

2020-10-22 14:20 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +  const NUMBER_OF_FAKES = 50;
why there ?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +    message: ' ',
space?

2020-10-22 14:20 UTC, oleksandrbazil commented on src/redux/usersListReducer.ts
> +    animationIn: ['animate__animated', 'animate__fadeIn'],
дублируеться?

2020-10-22 15:13 UTC, oleksandrbazil commented on src/components/Search/index.tsx
> +        onBlur={() => setTimeout(() => setIsResultsShow(false), 500)}
добавить TODO comment next pull request

2020-10-22 15:25 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +    setSrc(URL.createObjectURL(image));
исправить все повторения одним коммитом

2020-10-22 15:29 UTC, oleksandrbazil commented on src/db/index.ts
> +  db.table('users').delete(id);
добавить TODO comment next pull request

2020-10-22 15:29 UTC, oleksandrbazil commented on src/localStorage/index.ts
> +  return formState ? JSON.parse(formState) : undefined;
добавить TODO comment next pull request

2020-10-22 16:01 UTC, oleksandrbazil commented on src/db/index.ts
> +  db.table('users').delete(id);
user || {}

2020-10-22 16:02 UTC, oleksandrbazil commented on src/db/index.ts
> +  db.table('users').delete(id);
TODO comment проверить пропсы на уровне src/db/index 
id => integer?
user data => filter required fields

2020-10-23 07:33 UTC, oleksandrbazil requested changes

2020-10-23 07:33 UTC, oleksandrbazil commented on package.json
> +    "xhr": "^2.5.0",
если не используешь, убери зависимость

2020-10-23 07:33 UTC, oleksandrbazil commented on src/components/UsersList/Paginator/index.tsx
> +            [classNames.active]: page === value,
пожалуйста, переименуй value во что-то более понятное (currentPage?)

2020-10-23 07:33 UTC, oleksandrbazil commented on src/components/Search/index.tsx
> +        onBlur={() => setTimeout(() => setIsResultsShow(false), 500)}
не вижу TODO комментария, где он?

2020-10-23 07:33 UTC, oleksandrbazil commented on src/db/index.ts
> +  db.table('users').delete(id);
не вижу где TODO комментарий?

2020-10-23 07:33 UTC, oleksandrbazil commented on src/localStorage/index.ts
> +  return formState ? JSON.parse(formState) : undefined;
не вижу туду комментария

2020-10-23 07:35 UTC, vlad0k commented on package.json
> +    "xhr": "^2.5.0",
убрал

2020-10-23 07:42 UTC, vlad0k commented on src/components/UsersList/Paginator/index.tsx
> +            [classNames.active]: page === value,
+

2020-10-23 07:48 UTC, merged