Prereview5
vlad0k/wizard-form-react pull request #5
Opened 2020-10-23 11:16 UTC by vlad0k

2020-10-23 11:57 UTC, oleksandrbazil requested changes
в общем и целом уже лучше
Однако я вижу еще проблемы
Исправь плз то что я написал в комментах а потом я тебе опишу проблемы которые надо решить, ок?

2020-10-23 11:57 UTC, oleksandrbazil commented on src/components/StepWizard/FormLayout/index.tsx
> +  console.log(isEditMode);
👎

2020-10-23 11:57 UTC, oleksandrbazil commented on src/components/StepWizard/NavigationButtons/index.tsx
> +        return new Promise((resolve, reject) => reject());
а зачем это тут?

2020-10-23 11:57 UTC, oleksandrbazil commented on src/components/StepWizard/NavigationButtons/index.tsx
> +      .then(() => (nextUrl ? history.push(nextUrl) : history.push('/users')));
два раза пишешь history.push

2020-10-23 11:57 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +          const nextUrl = index + 1 !== STEPS.length ? match.url + '/' + STEPS[index + 1].url : '';
`index + 1 !== STEPS.length` это не `isFinish` ?

2020-10-23 11:57 UTC, oleksandrbazil commented on src/components/StepWizard/index_old.tsx
> +// import React, { FC, useEffect } from 'react';
закоментированный код - мертвый код => удаляй

2020-10-23 11:58 UTC, oleksandrbazil commented on src/components/StepWizard/NavigationButtons/index.tsx
> +        return new Promise((resolve, reject) => reject());
это я так понимаю вытекающая проблема, ничего с этим не делай пока что, мы ее решим чуть позже, оставь TODO comment

2020-10-23 14:10 UTC, oleksandrbazil requested changes

2020-10-23 14:10 UTC, oleksandrbazil commented on src/App.tsx
> +        <Route path="/edit/:id/:step">
как думаешь это правильный подход?
```
<Route path="/new/:step">
...
<Route path="/edit/:id/:step">
```

2020-10-23 14:10 UTC, oleksandrbazil commented on src/components/StepWizard/AccountForm/index.tsx
> +        <NavigationButtons
а почему нельзя передать NavigationButtons в 
```
<FormLayout
      initialValues={{ ...initialValues, passwordRepeat: initialValues.password }}
....
>
```

2020-10-23 14:10 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +  const { step } = useParams();
зачем?

2020-10-23 14:10 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +  const history = useHistory();
зачем?

2020-10-23 14:10 UTC, oleksandrbazil commented on src/components/ui/FieldError/index.tsx
> +      <div className={classNames.error}>
эммм, а это решило проблему?

2020-10-23 14:10 UTC, oleksandrbazil commented on src/components/ui/SelectField/index.module.css
> +  z-index: 100;
почему z-index 100?

2020-10-23 14:41 UTC, vlad0k commented on src/components/ui/FieldError/index.tsx
> +      <div className={classNames.error}>
Да

2020-10-26 12:43 UTC, oleksandrbazil requested changes

2020-10-26 12:43 UTC, oleksandrbazil commented on .eslintrc.json
> +        "no-unused-vars": "off",
почему добавил такое правило?

2020-10-26 12:43 UTC, oleksandrbazil commented on src/components/StepWizard/CapabilitiesForm/index.tsx
> +        {navButtons}
второй раз передаешь кнопки, может нам все-такие не надо FormLayout? или передавать props прямо в FormLayout?

2020-10-26 12:43 UTC, oleksandrbazil commented on src/components/StepWizard/ContactsForm/index.tsx
> +        {navButtons}
третий раз передаешь кнопки, может нам все-такие не надо FormLayout? или передавать props прямо в FormLayout?

2020-10-26 12:43 UTC, oleksandrbazil commented on src/components/StepWizard/NavigationButtons/index.tsx
> +    validateForm()
navigation button ничего не должны знать о validateForm

2020-10-26 12:43 UTC, oleksandrbazil commented on src/components/StepWizard/ProfileForm/index.tsx
> +        {navButtons}
четвертый раз передаешь кнопки, может нам все-такие не надо FormLayout? или передавать props прямо в FormLayout?

2020-10-26 12:43 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +                  nextUrl={!isFinish ? `${pathname}#${STEPS[index + 1].url}` : ''}
{pathname + '#' + STEPS[0].url}
${pathname}#${STEPS[index + 1].url}
${pathname}#${STEPS[index - 1].url}

Квест, найтиде 3 совпадения!

2020-10-26 16:18 UTC, vlad0k commented on .eslintrc.json
> +        "no-unused-vars": "off",
потому что оно переопределено ts, если у ес линт оно включено, то ругается при определении типа переменных функции

2020-10-26 17:53 UTC, vlad0k commented on src/components/StepWizard/ProfileForm/index.tsx
> +        {navButtons}
добавил кнопки в form layout

2020-10-26 17:54 UTC, vlad0k commented on src/components/StepWizard/index.tsx
> +                  nextUrl={!isFinish ? `${pathname}#${STEPS[index + 1].url}` : ''}
написал функцию (index) => pathname + '#' + STEPS[index].url;

2020-10-27 08:04 UTC, oleksandrbazil requested changes

2020-10-27 08:04 UTC, oleksandrbazil commented on src/components/StepWizard/RestoreUnsaved/index.tsx
> +    console.log(savedFormState.birthDate);
что нужно сделать для того что бы такие штуки не попадали в коммиты?

2020-10-27 08:04 UTC, oleksandrbazil commented on src/yup/index.ts
> +    const users = await getUsers();
было бы лучше отдать логику проверки email и username на сервер 
const result = await checkUser({username});
const result = await checkUser({email });
который возвращает true / false

2020-10-27 08:04 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +  const nextStep = (nextUrl: string) => {
логика отправки на регистрацию пользователя должна быть описана тут=> перенеси formSubmitHandler в nextStep
....

и мы с каждым шагом ближе к тому что нам не нужен FormLayout компонент :)

2020-10-27 08:04 UTC, oleksandrbazil commented on src/components/StepWizard/ProfileForm/index.tsx
> +      <InputField name="email" label="Email" />
Email Input должен иметь type email

2020-10-27 18:06 UTC, vlad0k commented on src/components/StepWizard/index.tsx
> +  const nextStep = (nextUrl: string) => {
Теперь я начинаю понимать))

2020-10-28 06:58 UTC, oleksandrbazil requested changes
👍 much better

2020-10-28 06:58 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +        dispatch(addUser({ ...form, ...values }));
что произойдет если запрос на сервер будет идти с задержкой?

2020-10-28 06:58 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +          const prevUrl = index > 0 ? createTabUrl(index - 1) : '';
как думаешь можно перенести эту логику в prevStep/nextStep ?

2020-10-28 06:58 UTC, oleksandrbazil commented on src/db/index.ts
> +export const checkUniqueValue = async (value: string | null = '', valueName: string) => {
то есть я могу с фронта сделать запросы и проверить есть ли пользователь с таким password?
может нужно все-таки ограничить поля по которым можно сделать проверку?

2020-10-28 06:58 UTC, oleksandrbazil commented on src/yup/index.ts
> +    return await checkUniqueValue(value ? value : '', 'username');
а случиться с формой если запрос вернет ошибку?

2020-10-28 06:58 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +    editMode || getCurrentStepByHash(hash) < currentStep
что является приоритетным при определении отображения текущей формы: redux currentStep или location hash?

2020-10-28 06:58 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +  }, [hash]);
какие переменные должны быть переданы как зависимости?

2020-10-28 06:58 UTC, oleksandrbazil commented on src/components/StepWizard/RestoreUnsaved/index.tsx
> +        avatar: null,
почему нужно затирать avatar и birthDate?

2020-10-29 08:42 UTC, vlad0k commented on src/components/StepWizard/index.tsx
> +          const prevUrl = index > 0 ? createTabUrl(index - 1) : '';
+

2020-10-29 09:31 UTC, vlad0k commented on src/db/index.ts
> +export const checkUniqueValue = async (value: string | null = '', valueName: string) => {
+

2020-10-29 09:32 UTC, vlad0k commented on src/components/StepWizard/index.tsx
> +  }, [hash]);
+

2020-10-29 13:06 UTC, oleksandrbazil requested changes

2020-10-29 13:06 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +    component: <ContactsForm />,
ничего делать не надо, просто хочу обратить внимание на то что задача стояла настроить валидацию для 2-х форм, а пришлось затрагивать валидационные схемы всех :)

2020-10-29 13:06 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +    const prevUrl = !isFirstStep ? createTabUrl(stepNumber - 1) : '';
а точно надо задавать переменную а потом проверять есть ли переменная?
может можно выполнить функцию если !isFirstStep?

2020-10-29 13:06 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +    const nextUrl = !isFinish ? createTabUrl(stepNumber + 1) : '';
nextUrl переменная не нужна

2020-10-29 13:06 UTC, oleksandrbazil commented on src/components/StepWizard/index.tsx
> +  const nextStep = (values: FormikValues, stepNumber: number, isFinish: boolean = false) => {
а почему столько аргументов у функции? можно же использовать обьект....

2020-10-29 13:06 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/DropZone/index.tsx
> +      <input {...getInputProps()} accept="image/*" />
а гифку можно поставить? :)

2020-10-29 13:06 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +        if (data.width < MIN_CROPPER_WIDTH) {
👍 , только у нас квадрат и походу можно  проверять сразу 2 значения
```
if (data.width < MIN_CROPPER_WIDTH || data.height < MIN_CROPPER_HEIGHT) {
...
}
```

2020-10-29 13:06 UTC, oleksandrbazil commented on src/components/ui/RadioGroup/index.tsx
> +      <FieldError name="gender" />
👎 hardcode name in /ui/RadioGroup

2020-10-29 13:06 UTC, oleksandrbazil commented on src/db/index.ts
> +  skipId: number = NaN,
как для тестового функция нормальная, но есть такая ремарка (как говорят на  англ For You Information):
1) skipId по сути = currentUserId, он обычно не передается явно, а определяется на бэке
2) будет все-таки лучши изначально передавать параметры в объекте первого аргумента, Почему? потому что параметры могут добавиться а  количество аргументов должно быть минимальное

2020-10-29 13:12 UTC, vlad0k commented on src/components/ui/RadioGroup/index.tsx
> +      <FieldError name="gender" />
oops

2020-10-29 13:30 UTC, vlad0k commented on src/components/StepWizard/index.tsx
> +    const prevUrl = !isFirstStep ? createTabUrl(stepNumber - 1) : '';
исправил

2020-10-29 13:32 UTC, vlad0k commented on src/components/StepWizard/index.tsx
> +    const nextUrl = !isFinish ? createTabUrl(stepNumber + 1) : '';
согласен

2020-10-29 13:41 UTC, vlad0k commented on src/components/StepWizard/index.tsx
> +  const nextStep = (values: FormikValues, stepNumber: number, isFinish: boolean = false) => {
Да, чтобы не путать порядок параметров

2020-10-29 13:45 UTC, vlad0k commented on src/components/ui/AvatarPicker/DropZone/index.tsx
> +      <input {...getInputProps()} accept="image/*" />
Теперь нельзя

2020-10-29 13:45 UTC, vlad0k commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +        if (data.width < MIN_CROPPER_WIDTH) {
Квадрат - частный случай прямоугольника

2020-10-29 13:53 UTC, vlad0k commented on src/db/index.ts
> +  skipId: number = NaN,
сделал объектом

2020-10-29 14:07 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +        if (data.width < MIN_CROPPER_WIDTH) {
и как я должен понять этот комментарий?

2020-10-29 14:23 UTC, vlad0k commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +        if (data.width < MIN_CROPPER_WIDTH) {
Я добавил константу SQUARE_CROPPER_SIZE
<img width="428" alt="image" src="https://user-images.githubusercontent.com/32240755/97586605-1eddab80-1a03-11eb-8054-8072f6c9aa74.png">

2020-10-29 14:24 UTC, oleksandrbazil approved these changes

2020-10-29 14:24 UTC, oleksandrbazil commented on src/yup/index.ts
> +      valueName: 'username',
можно было просто передать username как поле объекта

2020-10-29 14:26 UTC, vlad0k commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +        if (data.width < MIN_CROPPER_WIDTH) {
Я делаю тут таким образом с расчетом на то что Кроппер может стать прямоугольным

2020-10-29 14:27 UTC, oleksandrbazil commented on src/components/ui/AvatarPicker/ImageCrop/index.tsx
> +        if (data.width < MIN_CROPPER_WIDTH) {
у нас квадрат => высота == ширина =>, можно сделать проверку сразу и на ширину и на высоту и если что-то меньше 150 то установить двум полям по 150, а не разделять отдельно ширину, отдельно высоту
Понимаешь?

2020-10-29 14:30 UTC, vlad0k commented on src/yup/index.ts
> +      valueName: 'username',
?

2020-10-29 14:34 UTC, merged